batch_size    = 2048
dataset       = "dbbook"
epochs        = 500
learning_rate = 0.001
log           = false
seed          = 19
top_k         = [5, 10, 20, 50]

alpha             = false
autoencoder       = false
embedding_dim     = 512
ensemble_fusion   = false
freeze            = false
fusion_modalities = "mean"
fusion_type       = "late"
info_nce          = false
multimodal        = true
normalized        = false
n_layers          = 0
single_branch     = false

[datasets]
dbbook = ["images", "text"]
ml1m   = ["audio", "images", "text", "video"]
