batch_size = 2048
learning_rate = 0.001
dataset = "dbbook"
epochs = 1000
top_k = [5, 10, 20, 50]
seed = 19
early_stop_window = 20
early_stop_threshold = 1e-6
log = true

n_layers = 4
embedding_dim = 256
fusion_type = "early"
fusion_modalities = "mean"
autoencoder = false
multimodal = false
single_branch = false
bidirectional = false
freeze = true
ensemble_fusion = false

[datasets]
dbbook = ["images", "text"]
ml1m = ["audio", "images", "text", "video"]
