batch_size    = 2048
dataset       = "dbbook"
epochs        = 300
learning_rate = 0.001
log           = true
seed          = 19
top_k         = [10, 20, 5, 50]

alpha             = false
autoencoder       = false
embedding_dim     = 512
ensemble_fusion   = false
freeze            = true
fusion_modalities = "mean"
fusion_type       = "late"
multimodal        = true
n_layers          = 2
single_branch     = false

[datasets]
dbbook = ["images", "text"]
ml1m   = ["audio", "images", "text", "video"]
