n_layers = 3
device = "cuda"
batch_size = 2048
embedding_dim = 2048
learning_rate = 0.001
dataset = "dbbook"
epochs = 150
model = "ef-mmlgcn"
fusion = "mean"
top_k = [
    5,
    10,
    20,
    50,
]
seed = 19
multimodal = true

[datasets]
dbbook = [
    "images",
    "text",
]
ml1m = [
    "audio",
    "images",
    "text",
    "video",
]
