n_layers = 0
device = "cuda"
batch_size = 2048
embedding_dim = 1024
learning_rate = 0.001
dataset = "dbbook"
epochs = 150
model = "ef-mmlgcn"
fusion = "sum"
top_k = [
    5,
    10,
    20,
    50,
]
seed = 19
multimodal = true
single_branch = true
freeze = false

[datasets]
dbbook = [
    "images",
    "text",
]
ml1m = [
    "audio",
    "images",
    "text",
    "video",
]
