batch_size = 2048
learning_rate = 0.001
dataset = "dbbook"
epochs = 100
top_k = [5, 10, 20, 50]
seed = 19
log = true

n_layers = 2
embedding_dim = 256
fusion_type = "early"
fusion_modalities = "mean"
autoencoder = false
multimodal = true
single_branch = false
freeze = true
ensemble_fusion = false

[datasets]
dbbook = ["images", "text"]
ml1m = ["audio", "images", "text", "video"]
