# General
multimodal = true
embedding_dim = 256
n_layers = 2
epochs = 300
learning_rate = 0.001
log = true
seed = 19
top_k = [5, 10, 20, 50]
dataset = "ml1m"
batch_size = 8192

# Multimodal settings
single_branch = false
autoencoder = false
ensemble_fusion = false
freeze = false
fusion_modalities = "mean"
fusion_type = "late"
info_nce = false
weighting = false

[datasets]
dbbook = ["images", "text"]
ml1m = ["audio", "images", "text", "video"]
